version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3000'
    environment:
      MYSQL_HOST: segunda.cf4gic4aiuhl.us-east-2.rds.amazonaws.com
      MYSQL_USER: master
      MYSQL_PASSWORD: Davi1603
      MYSQL_DB: segunda
    volumes:
      - ./backend/uploads:/uploads
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'