version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3000'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: aplicacao
    volumes:
      - ./backend/uploads:/uploads
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
  mysql:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aplicacao
